env:
  es2021: true

root: true

parser: '@typescript-eslint/parser'

parserOptions:
  sourceType: module
  project: ./tsconfig.json

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

rules:
  max-len:
    - error
    - code: 120
  no-multiple-empty-lines:
    - error
    - max: 1
  no-var:
    - error
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowTypedFunctionExpressions: true
  '@typescript-eslint/quotes':
    - error
    - single
  '@typescript-eslint/object-curly-spacing':
    - error
    - always
  '@typescript-eslint/indent':
    - error
    - 2
    - SwitchCase: 1
      ignoredNodes:
        - PropertyDefinition[decorators]
        - TSUnionType
        - TSTypeParameterInstantiation
        - TSIntersectionType
  '@typescript-eslint/semi':
    - error
    - always
  '@typescript-eslint/comma-dangle':
    - error
    - always-multiline
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      args: after-used
      argsIgnorePattern: ^_
      caughtErrors: all
  '@typescript-eslint/no-empty-interface':
    - error
    - allowSingleExtends: true
  '@typescript-eslint/no-explicit-any':
    - error
    - hasSuggestions: true
