ls:
  .dir: regex:([.a-z0-9]*)([-.][a-z]+)*
  .scss: regex:([.a-z0-9]*)([-.][a-z]+)*
  .ts: regex:([.a-z0-9]*)([-.][a-z]+)*
  backend/src/data/migrations:
    .ts: snake_case

ignore:
  - node_modules
  - build
  - shared/build
  - shared/node_modules
  - frontend/build
  - frontend/node_modules
  - backend/build
  - backend/node_modules
  - .git
