enum ActionType {
  SET_PERSONAL_ROOM = 'racingSetPersonalRoom',
  SET_PERSONAL_ROOM_AS_CURRENT = 'racingSetPersonalRoomAsCurrent',
  LOAD_CURRENT_ROOM = 'racingLoadCurrentRoom',
  SET_CURRENT_ROOM = 'setCurrentRoom',
  LOAD_AVAILABLE_ROOMS = 'racingLoadAvailableRooms',
  ADD_ROOM_TO_AVAILABLE_ROOMS = 'racingAddRoomToAvailableRooms',
  REMOVE_ROOM_FROM_AVAILABLE_ROOMS = 'racingRemoveRoomFromAvailableRooms',
  LOAD_SHARE_ROOM_URL = 'loadShareRoomUrl',
  RESET_SHARE_ROOM_URL = 'racingResetShareRoomUrl',
  CREATE_ROOM = 'racingCreateRoom',
  SEND_ROOM_URL_TO_EMAILS = 'racingSendRoomUrlToEmails',
  SET_COMMENTATOR_TEXT = 'racingSetCommentatorText',
  ADD_PARTICIPANT = 'racingAddParticipant',
  REMOVE_PARTICIPANT = 'racingRemoveParticipant',
  RESET_IS_LOAD_CURRENT_ROOM_FAILED = 'racingResetIsLoadCurrentRoomFailed',
  TOGGLE_IS_GAME_STARTED = 'racingToggleIsGameStarted',
  TOGGLE_PARTICIPANT_IS_READY = 'racingToggleParticipantIsReady',
  SET_SPENT_SECONDS = 'racingSetSpentSeconds',
  INCREASE_CURRENT_PARTICIPANT_POSITION = 'increaseCurrentParticipantPosition',
  TOGGLE_CURRENT_PARTICIPANT_IS_READY = 'toggleCurrentParticipantIsReady',
  RESET_ALL = 'resetAll',
  RESET_AVAILABLE_ROOMS = 'resetResetAvailableRooms',
  RESET_CURRENT_ROOM_TO_DEFAULT = 'resetCurrentRoomToDefault',
}

export { ActionType };
